### ISSUE TITLE
May 2014 sprint master issue

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#339]
Things to do on Nengo
- [x] [Learning](https://github.com/ctn-waterloo/nengo/pull/303)
- [x] Probes
- [x] Work on issues in the [2.0.0 release milestone](https://github.com/ctn-waterloo/nengo/issues?milestone=4&page=1&state=open)
- [x] Make sure documentation is up to date (#371)
- [x] Finish TODO examples
- [x] Test / document installation process for various OSes (#371)
- [x] Implement decoder caching
- [x] Document and do examples for SPA
- [x] Different neuron models (#285)
- [x] Documentation generation: running ipython notebooks and nbconverting the contents should be done as part of making documentation
- [ ] IPython visualization of networks (delay?)
- [ ] Project website (using Github pages, maybe) (delay?)
- [x] Network validation / optimization (`optimization` branch)
- [x] Arbitrary synapse models

Things to do related to Nengo at the sprint (useful for battle testing Nengo)
- [x] Work on [nengo_gui](https://github.com/ctn-waterloo/nengo_gui) (interested parties should look into [d3.js](http://d3js.org/))
- [x] Work on [brainspawn](https://github.com/chairmanmeow50/Brainspawn)
