### ISSUE TITLE
Documentation ideas

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo#625]
If you have time, and can write about any of the items below, we'd love to build up our documentation even more. These are the leftovers from #371.

- [ ] Help with offline installation USB (see #200 for context; in progress [here](https://github.com/Seanny123/nengo_usb))
- [ ] Document how to run the example scripts (offline/online, Windows/Linux, iPython notebook and plain python)
- Documentation checkers
  - [ ] Check that all example notebooks are in the docs somewhere
- [ ] Nengo style guide (See #231)
- [ ] Document probes and timing (See #234 and #468) -- Backend Architecture doc in the Dev Guide
- [ ] Add dev notes from SPA rebase
- [ ] Document network / other object initialization process (see [this note](https://github.com/ctn-waterloo/nengo-temp/pull/394/files#r14463939)) -- Frontend Architecture doc in the Dev Guide
- [ ] SPA documentation
- [ ] Add a "guided tour" that teaches the NEF through links to various materials (examples, Terry's notes, etc)
- [ ] Document how py_test is used for the different back-ends, the various hooks and command-line arguments, the seeding of random numbers and plotting tests results;
- [ ] Review all examples in docstrings to ensure they run
  - [ ] Consider ensuring that they are `doctest` compatible and actually running the doctests to ensure that they're always valid
